# Generated by Django 3.0 on 2021-07-31 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myenv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
